//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowTractor.Plugins {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class PluginSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PluginSettings defaultInstance = ((PluginSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PluginSettings())));
        
        public static PluginSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?><ArrayOfPluginDefinition xmlns:xsi=\"http:/" +
            "/www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema" +
            "\" />")]
        public global::System.Collections.Generic.List<ShowTractor.Plugins.PluginDefinition> MetadataProviders {
            get {
                return ((global::System.Collections.Generic.List<ShowTractor.Plugins.PluginDefinition>)(this["MetadataProviders"]));
            }
            set {
                this["MetadataProviders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?><ArrayOfPluginDefinition xmlns:xsi=\"http:/" +
            "/www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema" +
            "\" />")]
        public global::System.Collections.Generic.List<ShowTractor.Plugins.PluginDefinition> MediaSourceProviders {
            get {
                return ((global::System.Collections.Generic.List<ShowTractor.Plugins.PluginDefinition>)(this["MediaSourceProviders"]));
            }
            set {
                this["MediaSourceProviders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?><ArrayOfPluginDefinition xmlns:xsi=\"http:/" +
            "/www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema" +
            "\" />")]
        public global::System.Collections.Generic.List<ShowTractor.Plugins.PluginDefinition> DownloadManagers {
            get {
                return ((global::System.Collections.Generic.List<ShowTractor.Plugins.PluginDefinition>)(this["DownloadManagers"]));
            }
            set {
                this["DownloadManagers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?><ArrayOfPluginDefinition xmlns:xsi=\"http:/" +
            "/www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema" +
            "\" />")]
        public global::System.Collections.Generic.List<ShowTractor.Plugins.PluginDefinition> MediaPlayers {
            get {
                return ((global::System.Collections.Generic.List<ShowTractor.Plugins.PluginDefinition>)(this["MediaPlayers"]));
            }
            set {
                this["MediaPlayers"] = value;
            }
        }
    }
}
