//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowTractor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShowTractor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: Jingchao Feng.
        /// </summary>
        public static string AuthorColonAuthorName {
            get {
                return ResourceManager.GetString("AuthorColonAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright: 2020 All rights rserved..
        /// </summary>
        public static string CopyrightColonCopyrightInfo {
            get {
                return ResourceManager.GetString("CopyrightColonCopyrightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string FilterBy_All {
            get {
                return ResourceManager.GetString("FilterBy_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string FilterBy_Downloaded {
            get {
                return ResourceManager.GetString("FilterBy_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded/Available to Stream.
        /// </summary>
        public static string FilterBy_DownloadedOrAvailableToStream {
            get {
                return ResourceManager.GetString("FilterBy_DownloadedOrAvailableToStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unwatched.
        /// </summary>
        public static string FilterBy_Unwatched {
            get {
                return ResourceManager.GetString("FilterBy_Unwatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSetingsPageTitle {
            get {
                return ResourceManager.GetString("GeneralSetingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default episode length.
        /// </summary>
        public static string GeneralSettingsCaptionDefaultEpisodeLength {
            get {
                return ResourceManager.GetString("GeneralSettingsCaptionDefaultEpisodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata refresh interval (minutes):.
        /// </summary>
        public static string GeneralSettingsCaptionMetadataUpdate {
            get {
                return ResourceManager.GetString("GeneralSettingsCaptionMetadataUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show checkbox in calendar page.
        /// </summary>
        public static string GeneralSettingsCaptionShowCheckboxInCalendarPage {
            get {
                return ResourceManager.GetString("GeneralSettingsCaptionShowCheckboxInCalendarPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string GeneralSettingsSubtitleCalendar {
            get {
                return ResourceManager.GetString("GeneralSettingsSubtitleCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata update.
        /// </summary>
        public static string GeneralSettingsSubtitleMetadataUpdate {
            get {
                return ResourceManager.GetString("GeneralSettingsSubtitleMetadataUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string GeneralSettingsSubtitleMiscellaneous {
            get {
                return ResourceManager.GetString("GeneralSettingsSubtitleMiscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When selected, a checkbox will be displayed in the calendar page to mark episodes as watched. Otherwise, a &quot;new&quot; icon is displayed for unwatched episodes..
        /// </summary>
        public static string GeneralSettingsTooltipShowCheckboxInCalendarPage {
            get {
                return ResourceManager.GetString("GeneralSettingsTooltipShowCheckboxInCalendarPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no current shows.
        /// </summary>
        public static string LibraryNoCurrentShows {
            get {
                return ResourceManager.GetString("LibraryNoCurrentShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your shows are running. Good!.
        /// </summary>
        public static string LibraryNoEndedShows {
            get {
                return ResourceManager.GetString("LibraryNoEndedShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to display here
        ///Search for a TV show to get started.
        /// </summary>
        public static string LibraryNoTvShows {
            get {
                return ResourceManager.GetString("LibraryNoTvShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-Z.
        /// </summary>
        public static string SortBy_AToZ {
            get {
                return ResourceManager.GetString("SortBy_AToZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SortBy_None {
            get {
                return ResourceManager.GetString("SortBy_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string SortBy_ReleaseDate {
            get {
                return ResourceManager.GetString("SortBy_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Series.
        /// </summary>
        public static string SortBy_TvSeries {
            get {
                return ResourceManager.GetString("SortBy_TvSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day.
        /// </summary>
        public static string TotalTimeDayFormat {
            get {
                return ResourceManager.GetString("TotalTimeDayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        public static string TotalTimeDayFormatPlural {
            get {
                return ResourceManager.GetString("TotalTimeDayFormatPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour.
        /// </summary>
        public static string TotalTimeHourFormat {
            get {
                return ResourceManager.GetString("TotalTimeHourFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string TotalTimeHourFormatPlural {
            get {
                return ResourceManager.GetString("TotalTimeHourFormatPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} month.
        /// </summary>
        public static string TotalTimeMonthFormat {
            get {
                return ResourceManager.GetString("TotalTimeMonthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months.
        /// </summary>
        public static string TotalTimeMonthFormatPlural {
            get {
                return ResourceManager.GetString("TotalTimeMonthFormatPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        public static string TotalTimeSeperator {
            get {
                return ResourceManager.GetString("TotalTimeSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} year.
        /// </summary>
        public static string TotalTimeYearFormat {
            get {
                return ResourceManager.GetString("TotalTimeYearFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years.
        /// </summary>
        public static string TotalTimeYearFormatPlural {
            get {
                return ResourceManager.GetString("TotalTimeYearFormatPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string VersionColon {
            get {
                return ResourceManager.GetString("VersionColon", resourceCulture);
            }
        }
    }
}
