//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowTractor.Plugins.LocalFile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShowTractor.Plugins.LocalFile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in Matching Logics.
        /// </summary>
        internal static string BuiltInMatchingLogics {
            get {
                return ResourceManager.GetString("BuiltInMatchingLogics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, a number of built-in logics are used to match season/episode number and show name, in addition to the regular expressions below. Otherwise, only the regular expressions are used..
        /// </summary>
        internal static string BuiltInMatchingLogicsSubtitle {
            get {
                return ResourceManager.GetString("BuiltInMatchingLogicsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode Number.
        /// </summary>
        internal static string EpisodeNumberPatternName {
            get {
                return ResourceManager.GetString("EpisodeNumberPatternName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A regular expression to match TV episode number. The result should be in the first capture group..
        /// </summary>
        internal static string EpisodeNumberPatternSubtitle {
            get {
                return ResourceManager.GetString("EpisodeNumberPatternSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Location.
        /// </summary>
        internal static string SearchLocationName {
            get {
                return ResourceManager.GetString("SearchLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to search for local media files..
        /// </summary>
        internal static string SearchLocationSubtitle {
            get {
                return ResourceManager.GetString("SearchLocationSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Pattern.
        /// </summary>
        internal static string SearchPatternName {
            get {
                return ResourceManager.GetString("SearchPatternName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        internal static string SeasonPatternName {
            get {
                return ResourceManager.GetString("SeasonPatternName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A regular expression to match TV season number. The result should be in the first capture group..
        /// </summary>
        internal static string SeasonPatternSubtitle {
            get {
                return ResourceManager.GetString("SeasonPatternSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Name.
        /// </summary>
        internal static string ShowNamePatternName {
            get {
                return ResourceManager.GetString("ShowNamePatternName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A regular expression to match TV show name. The result should be in the first capture group. .
        /// </summary>
        internal static string ShowNamePatternSubtitle {
            get {
                return ResourceManager.GetString("ShowNamePatternSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Name Replacement Charactors.
        /// </summary>
        internal static string ShowNameReplacementCharactorsName {
            get {
                return ResourceManager.GetString("ShowNameReplacementCharactorsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following charactors in the matched Show Name will be ignored when looking up followed show names..
        /// </summary>
        internal static string ShowNameReplacementCharactorsSubtitle {
            get {
                return ResourceManager.GetString("ShowNameReplacementCharactorsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Built-in Matching Logics.
        /// </summary>
        internal static string UseBuiltInMatchingLogics {
            get {
                return ResourceManager.GetString("UseBuiltInMatchingLogics", resourceCulture);
            }
        }
    }
}
